# Generated by Django 5.2.5 on 2025-08-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imdb_api", "0005_review_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="av_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="number_rating",
            field=models.IntegerField(default=0),
        ),
    ]
