# Generated by Django 5.2.5 on 2025-08-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imdb_api", "0006_watchlist_av_rating_watchlist_number_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watchlist",
            old_name="av_rating",
            new_name="Average_rating",
        ),
        migrations.RenameField(
            model_name="watchlist",
            old_name="number_rating",
            new_name="Number_Rating",
        ),
    ]
